# The first FROM is now a stage called build-stage
FROM node:24 AS build-stage

ENV VITE_BACKEND_URL=/

WORKDIR /usr/src/app
COPY . .

RUN npm ci

RUN npm run build


FROM node:24 AS test-stage
WORKDIR /usr/src/app

COPY --from=build-stage /usr/src/app /usr/share/app

RUN npm ci

RUN npm run test


# This is a new stage, everything before this is gone, except for the files that we want to COPY
FROM nginx:1.29-alpine AS final-stage

# COPY the directory dist from the build-stage to /usr/share/nginx/html
# The target location here was found from the Docker hub page
COPY --from=build-stage /usr/src/app/dist /usr/share/nginx/html

